import type { ReactNode } from "react";
import clsx from "clsx";
import {
  BadgeCheck,
  CalendarClock,
  Check,
  ClipboardCheck,
  Clock,
  ListChecks,
  MessagesSquare,
  Share2,
  TrendingDown,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import Eyebrow from "@/components/ui/Eyebrow";
import styles from "./Capabilities.module.css";

/* ==========================================================================
   Preview panels
   They describe how each capability is structured. No sample candidates,
   scores or metrics are shown.
   ========================================================================== */

interface Tile {
  title: string;
  description: string;
  icon: LucideIcon;
}

function PreviewFrame({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <div className={styles.preview} role="group" aria-label={`${title} overview`}>
      <div className={styles.chrome} aria-hidden="true">
        <span className={styles.dot} />
        <span className={styles.dot} />
        <span className={styles.dot} />
        <span className={`${styles.chromeTitle} mono-label`}>{title}</span>
      </div>
      <div className={styles.previewBody}>{children}</div>
    </div>
  );
}

const SCREENING_STEPS = [
  {
    title: "Upload",
    description: "PDF or DOCX CVs arrive from the careers page or from your recruiters.",
  },
  {
    title: "Parse",
    description: "Skills, roles, education and dates are extracted into structured fields.",
  },
  {
    title: "Score",
    description: "Each candidate is matched to the role, with the reasoning written out.",
  },
];

function ScreeningPreview() {
  return (
    <PreviewFrame title="CV screening">
      <ol className={styles.steps}>
        {SCREENING_STEPS.map((step, index) => (
          <li key={step.title} className={styles.step}>
            <span className={styles.stepNum} aria-hidden="true">
              {String(index + 1).padStart(2, "0")}
            </span>
            <span className={styles.stepText}>
              <span className={styles.stepTitle}>{step.title}</span>
              <span className={styles.stepDesc}>{step.description}</span>
            </span>
          </li>
        ))}
      </ol>
    </PreviewFrame>
  );
}

const PIPELINE_COLUMNS = [
  { stage: "Applied", cards: 2 },
  { stage: "Screening", cards: 3 },
  { stage: "Interview", cards: 2 },
  { stage: "Offer", cards: 1 },
  { stage: "Hired", cards: 1 },
];

function PipelinePreview() {
  return (
    <PreviewFrame title="Pipeline">
      <div className={styles.board}>
        <div className={styles.boardInner}>
          {PIPELINE_COLUMNS.map((column) => (
            <div key={column.stage} className={styles.col}>
              <span className={`${styles.colHead} mono-label`}>{column.stage}</span>
              {Array.from({ length: column.cards }).map((_, index) => (
                <div
                  key={index}
                  className={clsx(
                    styles.skeleton,
                    column.stage === "Hired" && styles.skeletonDone
                  )}
                  aria-hidden="true"
                >
                  <span className={styles.bar} />
                  <span className={clsx(styles.bar, styles.barShort)} />
                </div>
              ))}
            </div>
          ))}
        </div>
      </div>
      <p className={`${styles.caption} mono-label`}>Layout preview</p>
    </PreviewFrame>
  );
}

function TileGrid({ tiles }: { tiles: Tile[] }) {
  return (
    <ul className={styles.tiles}>
      {tiles.map((tile) => {
        const Icon = tile.icon;
        return (
          <li key={tile.title} className={styles.tile}>
            <span className={styles.tileIcon} aria-hidden="true">
              <Icon size={18} strokeWidth={2} />
            </span>
            <div>
              <p className={styles.tileTitle}>{tile.title}</p>
              <p className={styles.tileDesc}>{tile.description}</p>
            </div>
          </li>
        );
      })}
    </ul>
  );
}

const INTERVIEW_TILES: Tile[] = [
  {
    title: "Schedule",
    description: "Coordinate candidates and interviewers in one place.",
    icon: CalendarClock,
  },
  {
    title: "Question kit",
    description: "Role-specific questions generated by AI.",
    icon: ListChecks,
  },
  {
    title: "Scorecard",
    description: "One rubric shared by every interviewer.",
    icon: ClipboardCheck,
  },
  {
    title: "Debrief",
    description: "Feedback side by side before the decision.",
    icon: MessagesSquare,
  },
];

const ANALYTICS_TILES: Tile[] = [
  {
    title: "Time to hire",
    description: "Days from application to accepted offer.",
    icon: Clock,
  },
  {
    title: "Stage drop-off",
    description: "Where candidates leave the funnel.",
    icon: TrendingDown,
  },
  {
    title: "Source quality",
    description: "Which channels actually produce hires.",
    icon: Share2,
  },
  {
    title: "Offer acceptance",
    description: "Offers accepted compared with declined.",
    icon: BadgeCheck,
  },
];

/* ==========================================================================
   Features
   `id` values must match the hash links in FloatingNav.
   ========================================================================== */

interface Feature {
  id: string;
  title: string;
  description: string;
  points: string[];
  preview: ReactNode;
}

const FEATURES: Feature[] = [
  {
    id: "ai-screening",
    title: "Every CV read, scored and explained.",
    description:
      "Upload a CV and HireCore extracts skills, experience and education into structured fields, then scores the candidate against the role. Each score comes with the reasoning behind it, so recruiters can trust it and challenge it.",
    points: [
      "Structured parsing for PDF and DOCX CVs",
      "Per-skill match with written reasoning",
      "A ranked shortlist for every open role",
    ],
    preview: <ScreeningPreview />,
  },
  {
    id: "pipeline",
    title: "One board for every candidate.",
    description:
      "Move candidates through configurable stages from a single board. Every move is logged and every stage has an owner, so nobody has to ask where a candidate stands.",
    points: [
      "Drag-and-drop stages for each job",
      "Stage history and a full audit trail",
      "Natural-language actions through the recruiter agent",
    ],
    preview: <PipelinePreview />,
  },
  {
    id: "interviews",
    title: "From scheduling to scorecard.",
    description:
      "Plan interviews, generate role-specific question kits and collect structured feedback from every interviewer, all in the same place the candidate lives.",
    points: [
      "AI-generated question kits for each role",
      "Shared scorecards built on a common rubric",
      "Hiring managers see all feedback in one view",
    ],
    preview: (
      <PreviewFrame title="Interviews">
        <TileGrid tiles={INTERVIEW_TILES} />
      </PreviewFrame>
    ),
  },
  {
    id: "analytics",
    title: "See where hiring slows down.",
    description:
      "Track how long roles take to fill, where candidates drop off and which sources lead to hires, broken down by role, team and workspace.",
    points: [
      "Time-to-hire and stage drop-off",
      "Source and channel quality",
      "Alerts when a pipeline stalls",
    ],
    preview: (
      <PreviewFrame title="Analytics">
        <TileGrid tiles={ANALYTICS_TILES} />
      </PreviewFrame>
    ),
  },
];

export default function Capabilities() {
  return (
    <section
      id="platform"
      className={styles.section}
      aria-labelledby="capabilities-title"
    >
      <div className="container">
        <header className={styles.header}>
          <Eyebrow>Platform</Eyebrow>
          <h2 id="capabilities-title" className={`${styles.title} text-fade`}>
            Everything between applied and hired.
          </h2>
          <p className={styles.lead}>
            Screening, pipeline, interviews and analytics share one data model, so
            nothing is copied between tools and nothing gets lost between stages.
          </p>
        </header>

        <div className={styles.rows}>
          {FEATURES.map((feature, index) => (
            <article
              key={feature.id}
              id={feature.id}
              className={clsx(styles.row, index % 2 === 1 && styles.rowReverse)}
            >
              <div className={styles.copy}>
                <p className={`${styles.index} mono-label`}>
                  {String(index + 1).padStart(2, "0")}
                </p>
                <h3 className={styles.heading}>{feature.title}</h3>
                <p className={styles.description}>{feature.description}</p>
                <ul className={styles.points}>
                  {feature.points.map((point) => (
                    <li key={point} className={styles.point}>
                      <span className={styles.check} aria-hidden="true">
                        <Check size={13} strokeWidth={3} />
                      </span>
                      {point}
                    </li>
                  ))}
                </ul>
              </div>

              {feature.preview}
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}